### ISSUE TITLE
Какая к черту годовая подписка???

### ISSUE THREAD

**Issue by parklir** [mohaxspb/ScpFoundationCore#140]
Раньше можно было купить безлимитную что стало?

**Comment by mohaxspb** [comment]
@parklir и вам добрый вечер. Вы что-то напутали. Никогда нельзя было безлимитную версию купить. Когда-то можно было лишь пользоваться приложением бесплатно и без ограничений. Но, т.к. пожертвований было мало мы не смогли поддерживать приложение бесплатным.
