### ISSUE TITLE
Combine everything to make one app?

### ISSUE THREAD

**Issue by TacoTheDank** [mohaxspb/ScpFoundationCore#208]
Surely you can't just keep making new apps with every new language that starts being supported? Why not combine all the apps into one and have the app detect the phone's system language?
I do see a lot of problems that would come forth with this, with the way the project is currently set up, but it's more of an idea at the moment.

**Comment by mohaxspb** [comment]
@TacoTheDank, hello!

Yes, I plan to combine all aps in one and already work on this. I wish to release it at summer.

**Comment by TacoTheDank** [comment]
Great!
