### ISSUE TITLE
Платные услуги не работают

### ISSUE THREAD

**Issue by parklir** [mohaxspb/ScpFoundationCore#237]
Вот не могу ничего купить и тд хотя бы чтобы список статей был больше 10 в офлайне. Как теперь быть?

**Comment by mohaxspb** [comment]
@parklir приложение удалено гуглом из Play Market вместе с почти всеми остальными приложениями в которых есть `SCP Foundation` в названии. Засим и покупки не работают. Подробнее тут: https://scpfoundation.app/scp/gp-problem/

Однако мы выложили приложение в магазин Amazona. Там всё работает. Ссылки и инструкции тут: https://scpfoundation.app/?utm_source=github.com&utm_medium=directLink&utm_campaign=issues_237
