### ISSUE TITLE
Publish in F-Droid

### ISSUE THREAD

**Issue by linsui** [mohaxspb/ScpFoundationCore#238]
Could you  publish this app in F-Droid?

**Comment by mohaxspb** [comment]
@linsui yes, I can do it. But, as I know, there are some requirements to publish to F-Droid. If I correctly understand, I need to remove some libs from app and make a license to source code and so on. 

It's not in first priority for me now. First of all I want to create API for this app, then totally rewrite it, then make an iOS version and then, maybe, I'll have time to think about F-Droid.

So, if I'll do it, I'll do it not in this or next year.
