### ISSUE TITLE
Images in app are not shown

### ISSUE THREAD

**Issue by joni999** [mohaxspb/ScpFoundationCore#239]
Hi there,
I can't view any images on the current Amazon marketplace app version. They don't seem to load. It shows some kind of placeholder instead
This happens on every Article.
 Everything else works perfectly fine.

I hope this screenshot actually works:

![Screenshot_20191127-191949](https://user-images.githubusercontent.com/58270144/69749540-fdb57080-114a-11ea-9b73-0dc2e0885ee0.jpg)

If I can provide any logs just tell me where to find them and I will provide them.
Best Regards and thank you for your work.

**Comment by mohaxspb** [comment]
@joni999 Hi!

This is a feature, not bug) Images will work after 24 hours from app install. You can see how it works here: https://github.com/mohaxspb/ScpFoundationCore/blob/5d70bcab42af875ba2aaf51bd63dd283ec6c6e29/core/src/main/java/ru/kuchanov/scpcore/manager/MyPreferenceManager.java#L792-L797
