### ISSUE TITLE
Please make this app available outside of Amazon

### ISSUE THREAD

**Issue by ElonSatoshi** [mohaxspb/ScpFoundationCore#240]
Release the app on Github releases, or f-droid, or Aptoide.

**Comment by mohaxspb** [comment]
@ElonSatoshi hello!

App now available at our site via direct APK download: https://scpfoundation.app/

Also, this repository is deprecated now and won't be updated. We recently released totally rewrited international version of app, which is also available at our site as APK: https://scpfoundation.app/

We will work only on new version and plan to release it at Huawei and Amazon stores and, maybe at Google Play. Then we'll work on iOS version.

So now we don't plan to release on other stores. And on F-Droid too, as (maybe I'm wrong) they don't allow to publish apps without open sources code (new version now is closed, but we'll open it soon) and with some SDKs, that collects user data (i.e. Facebook, Google etc, used for social auth)
